### ISSUE TITLE
AssertionError on attempt to pass invalid JSON-LD

### ISSUE THREAD

**Issue by TGNThump** [kbss-cvut/jb4jsonld#19]
An assertion fails when JsonLdProcessor.expand returns an empty list in JacksonJsonLdDeserializer::deserialize if the input is not expandable or valid jsonld.

```java
java.lang.AssertionError
	at cz.cvut.kbss.jsonld.deserialization.expanded.ExpandedJsonLdDeserializer.deserialize(ExpandedJsonLdDeserializer.java:42)
	at cz.cvut.kbss.jsonld.jackson.deserialization.JacksonJsonLdDeserializer.deserialize(JacksonJsonLdDeserializer.java:63)
	at cz.cvut.kbss.jsonld.jackson.deserialization.JacksonJsonLdDeserializer.deserializeWithType(JacksonJsonLdDeserializer.java:102)
```

An exception would likely be better in this case to allow for logical error handling in downstream applications.

**Comment by ledsoft** [comment]
Fixed in 0.6.0.
