### ISSUE TITLE
Ability to assume target type if not provided in jsonld.

### ISSUE THREAD

**Issue by TGNThump** [kbss-cvut/jb4jsonld#21]
Currently in [ActivityStreams4J](https://github.com/TGNThump/ActivityStreams4J), when a target type parameter is missing from the jsonld, an exception ocurs:
```
{
  "@context" : "https://www.w3.org/ns/activitystreams",
  "name" : "Foo",
  "id" : "http://example.org/foo"
}
```

```java
cz.cvut.kbss.jsonld.exception.TargetTypeException: Neither class social.pantheon.activitystreams4j.core.ObjectDTO nor any of its subclasses matches the types [].

	at cz.cvut.kbss.jsonld.deserialization.util.TargetClassResolver.getTargetClass(TargetClassResolver.java:53)
	at cz.cvut.kbss.jsonld.deserialization.expanded.Deserializer.resolveTargetClass(Deserializer.java:45)
```
It would be great if there was a way to specify that JB4JSONLD was allowed to assume the type of the object to be the base class it was told to serialize if no type parameter was provided.

**Comment by TGNThump** [comment]
With this configuration option enabled, I'm seeing a new AssertionError for some inputs;

```java
java.lang.AssertionError
  at cz.cvut.kbss.jsonld.deserialization.InstanceContext.setIdentifierValue(InstanceContext.java:59)
  at cz.cvut.kbss.jsonld.deserialization.DefaultInstanceBuilder.openObject(DefaultInstanceBuilder.java:121)
  at cz.cvut.kbss.jsonld.deserialization.expanded.ObjectDeserializer.openObject(ObjectDeserializer.java:69)
  at cz.cvut.kbss.jsonld.deserialization.expanded.ObjectDeserializer.processValue(ObjectDeserializer.java:49)
  at cz.cvut.kbss.jsonld.deserialization.expanded.CollectionDeserializer.resolveValue(CollectionDeserializer.java:74)
  at cz.cvut.kbss.jsonld.deserialization.expanded.CollectionDeserializer.processValue(CollectionDeserializer.java:52)
  at cz.cvut.kbss.jsonld.deserialization.expanded.ObjectDeserializer.processValue(ObjectDeserializer.java:57)
  at cz.cvut.kbss.jsonld.deserialization.expanded.ExpandedJsonLdDeserializer.deserialize(ExpandedJsonLdDeserializer.java:51)
  at cz.cvut.kbss.jsonld.jackson.deserialization.JacksonJsonLdDeserializer.deserialize(JacksonJsonLdDeserializer.java:62)
```

Here's an example input;
```json
{
  "@context" : "https://www.w3.org/ns/activitystreams",
  "id" : "http://polls.example.org/question/1",
  "name" : "A question about robots",
  "type" : "Question",
  "content" : "I'd like to build a robot to feed my cat. Which platform is best?",
  "oneOf" : [ {
    "name" : "arduino"
  }, {
    "name" : "raspberry pi"
  } ]
}
```

**Comment by ledsoft** [comment]
Ok, I'll look into it. What is the target type?

**Comment by TGNThump** [comment]
The target type is [ObjectDTO](https://github.com/TGNThump/ActivityStreams4J/blob/master/src/main/java/social/pantheon/activitystreams4j/core/ObjectDTO.java).

**Comment by ledsoft** [comment]
Try version 0.7.1. The problem was with values of the `oneOf` attribute. Because there's no type info on them, they were deserialized as `Object`, which doesn't have an identifier attribute. I've modified the library to skip the identifier field check in cases when there's no id in the JSON-LD either.

**Comment by TGNThump** [comment]
Thanks, that workes great.
